//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSM_Puppies.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640, 640")]
        public global::System.Drawing.Size PlayingFieldDimensions {
            get {
                return ((global::System.Drawing.Size)(this["PlayingFieldDimensions"]));
            }
            set {
                this["PlayingFieldDimensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public float Toy_Ball_Fun {
            get {
                return ((float)(this["Toy_Ball_Fun"]));
            }
            set {
                this["Toy_Ball_Fun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float Activity_Idle_WaitingTime {
            get {
                return ((float)(this["Activity_Idle_WaitingTime"]));
            }
            set {
                this["Activity_Idle_WaitingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public float Activity_RunToObject_CloseEnough {
            get {
                return ((float)(this["Activity_RunToObject_CloseEnough"]));
            }
            set {
                this["Activity_RunToObject_CloseEnough"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public float Pet_Puppy_MaxSpeed {
            get {
                return ((float)(this["Pet_Puppy_MaxSpeed"]));
            }
            set {
                this["Pet_Puppy_MaxSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public float Activity_ChaseBall_KickDistance {
            get {
                return ((float)(this["Activity_ChaseBall_KickDistance"]));
            }
            set {
                this["Activity_ChaseBall_KickDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.5")]
        public float Activity_RunToObject_Energy {
            get {
                return ((float)(this["Activity_RunToObject_Energy"]));
            }
            set {
                this["Activity_RunToObject_Energy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string Activity_ChaseBall_Fun {
            get {
                return ((string)(this["Activity_ChaseBall_Fun"]));
            }
            set {
                this["Activity_ChaseBall_Fun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Toy_SleepingMat_Energy {
            get {
                return ((float)(this["Toy_SleepingMat_Energy"]));
            }
            set {
                this["Toy_SleepingMat_Energy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Toy_Ball_Energy {
            get {
                return ((float)(this["Toy_Ball_Energy"]));
            }
            set {
                this["Toy_Ball_Energy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public float Toy_SleepingMat_Fun {
            get {
                return ((float)(this["Toy_SleepingMat_Fun"]));
            }
            set {
                this["Toy_SleepingMat_Fun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.5")]
        public float Activity_Idle_Fun {
            get {
                return ((float)(this["Activity_Idle_Fun"]));
            }
            set {
                this["Activity_Idle_Fun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.1")]
        public float Activity_Idle_Energy {
            get {
                return ((float)(this["Activity_Idle_Energy"]));
            }
            set {
                this["Activity_Idle_Energy"] = value;
            }
        }
    }
}
